project: cpp-opengl-glfw-glad-cmake
description: >
  Template for C++ projects with cross-platform Graphical User Interface (GUI) 
  implemented using OpenGL, GLFW, and GLAD, imported and built using CMake.
language: C++
environment: CMake, Make
requires:
  - Git
  - CMake
  - Make
  - Clang
startup:
  - nvim . --(open editor at project root)
other:
  - ./scripts/build-debug.sh    --(build the debug configuration)
  - ./scripts/build-release.sh  --(build the release configuration)
  - ./scripts/run-debug.sh      --(run the application with debug config)
  - ./scripts/run-release.sh    --(run the application with release config)
  - ./scripts/clean.sh          --(remove build-debug/ and build-release/) 

